name: build and run tests

on:
  push:
    branches:
      - "main"
      - "Develop"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  call-Build-workflow:
    uses: ./.github/workflows/RestoreAndBuildDotnetProjects.yml
  run-test:
    runs-on: ubuntu-latest
    needs: call-Build-workflow
    steps:
      - uses: actions/checkout@v5
      - name: Download a single artifact
        uses: actions/download-artifact@v5
        with:
          name: build-result
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
      - name: Test with the dotnet CLI
        run: dotnet test ./WebApplicationXGO.sln --no-build --artifacts-path artifacts
